# Generated by Django 6.0.6 on 2026-07-23 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_onboarding_completed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='onboarding_completed_at',
        ),
    ]
