# Generated by Django 6.0.6 on 2026-07-01 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField()),
                ("icon", models.CharField(default="bi-award-fill", max_length=40)),
                (
                    "criteria_type",
                    models.CharField(
                        choices=[
                            ("SESSION_COUNT", "Session Count"),
                            ("EMPATHY_SCORE", "Empathy Score"),
                            ("BOUNDARY_SCORE", "Boundary Score"),
                            ("IMPROVEMENT_DELTA", "Improvement Delta"),
                            ("SCENARIO_COUNT", "Scenario Count"),
                            ("REFLECTION_COUNT", "Reflection Count"),
                        ],
                        max_length=30,
                    ),
                ),
                ("criteria_value", models.PositiveIntegerField()),
                ("points", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PlatformSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "singleton_key",
                    models.CharField(default="default", max_length=20, unique=True),
                ),
                ("platform_name", models.CharField(default="PeerTrain", max_length=100)),
                (
                    "institution_name",
                    models.CharField(default="University Research Centre", max_length=255),
                ),
                (
                    "research_contact_email",
                    models.EmailField(default="research@university.ac.uk", max_length=254),
                ),
                (
                    "default_session_language",
                    models.CharField(default="English (UK)", max_length=50),
                ),
                ("max_exchanges_per_session", models.PositiveIntegerField(default=20)),
                (
                    "email_notifications_for_new_registrations",
                    models.BooleanField(default=True),
                ),
                ("automatic_session_feedback", models.BooleanField(default=True)),
                ("public_progress_profiles", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Platform Setting",
                "verbose_name_plural": "Platform Settings",
            },
        ),
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ROLE_PLAY", "Role-play"),
                            ("FEEDBACK", "Feedback"),
                            ("REFLECTION", "Reflection"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["type", "name"],
            },
        ),
        migrations.CreateModel(
            name="Scenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField()),
                (
                    "boundary_type",
                    models.CharField(
                        choices=[
                            ("EMOTIONAL", "Emotional Boundary"),
                            ("PRIVACY", "Privacy Boundary"),
                            ("REFERRAL", "Referral Boundary"),
                            ("BURNOUT", "Burnout & Compassion Fatigue"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("BEGINNER", "Beginner"),
                            ("INTERMEDIATE", "Intermediate"),
                            ("ADVANCED", "Advanced"),
                        ],
                        max_length=20,
                    ),
                ),
                ("estimated_duration_min", models.PositiveIntegerField()),
                ("learning_objectives", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="TrainingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "In progress"),
                            ("COMPLETED", "Completed"),
                            ("ABANDONED", "Abandoned"),
                        ],
                        default="IN_PROGRESS",
                        max_length=20,
                    ),
                ),
                ("overall_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "prompt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="training_sessions",
                        to="training.prompt",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="training.scenario",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="Reflection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reflection_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prompt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reflections",
                        to="training.prompt",
                    ),
                ),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reflection",
                        to="training.trainingsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender_type",
                    models.CharField(
                        choices=[("USER", "User"), ("AI", "AI")],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="training.trainingsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("overall_score", models.PositiveSmallIntegerField()),
                ("strengths", models.TextField()),
                ("improvements", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prompt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feedback_entries",
                        to="training.prompt",
                    ),
                ),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="training.trainingsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FeedbackScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criterion",
                    models.CharField(
                        choices=[
                            ("EMPATHY", "Empathy"),
                            ("BOUNDARY_AWARENESS", "Boundary Awareness"),
                            ("REFERRAL_AWARENESS", "Referral Awareness"),
                            ("COMMUNICATION_SKILLS", "Communication Skills"),
                        ],
                        max_length=40,
                    ),
                ),
                ("score", models.PositiveSmallIntegerField()),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="training.feedback",
                    ),
                ),
            ],
            options={
                "ordering": ["criterion"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("feedback", "criterion"),
                        name="unique_feedback_score_per_criterion",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earned_by",
                        to="training.achievement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earned_achievements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-earned_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "achievement"),
                        name="unique_user_achievement",
                    )
                ],
            },
        ),
    ]
