# Generated by Django 6.0.6 on 2026-07-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0002_prompt_scenario"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="response_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Unknown"),
                    ("USER_INPUT", "User Input"),
                    ("SCRIPTED", "Scripted"),
                    ("OPENAI", "OpenAI"),
                    ("GEMINI", "Gemini"),
                    ("PLACEHOLDER", "Placeholder"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
