# Generated by Django 6.0.6 on 2026-07-03 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0003_message_response_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackReviewItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("turn_index", models.PositiveSmallIntegerField(default=0)),
                ("message_excerpt", models.TextField()),
                ("issue_label", models.CharField(max_length=120)),
                ("why_it_matters", models.TextField()),
                ("better_reply", models.TextField()),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_items",
                        to="training.feedback",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review_items",
                        to="training.message",
                    ),
                ),
            ],
            options={
                "ordering": ["turn_index", "id"],
            },
        ),
    ]
