# Generated by Django 6.0.6 on 2026-07-09 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0005_feedback_generation_sources"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userachievement",
            name="unique_user_achievement",
        ),
        migrations.RemoveField(
            model_name="userachievement",
            name="achievement",
        ),
        migrations.RemoveField(
            model_name="userachievement",
            name="user",
        ),
        migrations.DeleteModel(
            name="Achievement",
        ),
        migrations.DeleteModel(
            name="UserAchievement",
        ),
    ]
