# Generated by Django 6.0.6 on 2026-07-09 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0006_remove_userachievement_unique_user_achievement_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="platformsetting",
            name="email_notifications_for_new_registrations",
        ),
        migrations.RemoveField(
            model_name="platformsetting",
            name="public_progress_profiles",
        ),
    ]
