# Generated by Django 6.0.6 on 2026-07-15 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_remove_platformsetting_email_notifications_for_new_registrations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformsetting',
            name='institution_name',
        ),
        migrations.RemoveField(
            model_name='platformsetting',
            name='platform_name',
        ),
        migrations.RemoveField(
            model_name='platformsetting',
            name='research_contact_email',
        ),
    ]
