# Generated by Django 6.0.6 on 2026-07-15 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_remove_platformsetting_institution_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformsetting',
            name='automatic_session_feedback',
        ),
    ]
