# Generated by Django 6.0.6 on 2026-07-15 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_remove_platformsetting_automatic_session_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformsetting',
            name='default_session_language',
        ),
    ]
