# Generated by Django 6.0.6 on 2026-07-22 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_remove_platformsetting_default_session_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='difficulty',
        ),
    ]
