# Generated by Django 6.0.6 on 2026-07-23 17:34

from django.db import migrations, models


def align_boundary_rubric_scenario_titles(apps, schema_editor):
    Scenario = apps.get_model("training", "Scenario")
    titles = {
        "EMOTIONAL": "Agency Boundary",
        "BURNOUT": "Supporter Relationship Boundary",
        "REFERRAL": "Safety & Escalation Boundary",
        "PRIVACY": "Integrated Boundary Practice",
    }
    for boundary_type, title in titles.items():
        Scenario.objects.filter(boundary_type=boundary_type).update(title=title)


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_align_boundary_taxonomy'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='rubric_version',
            field=models.CharField(default='BOUNDARY-SKILLS-1.0', max_length=30),
        ),
        migrations.AddField(
            model_name='feedbackreviewitem',
            name='boundary_key',
            field=models.CharField(choices=[('AGENCY', 'Agency Boundary'), ('RELATIONSHIP', 'Supporter Relationship Boundary'), ('SAFETY', 'Safety & Escalation Boundary')], default='AGENCY', max_length=20),
        ),
        migrations.AddField(
            model_name='feedbackscore',
            name='evidence',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='feedbackscore',
            name='next_move',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='feedbackscore',
            name='observed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feedbackscore',
            name='rationale',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='feedbackscore',
            name='rubric_version',
            field=models.CharField(default='BOUNDARY-SKILLS-1.0', max_length=30),
        ),
        migrations.AddField(
            model_name='reflection',
            name='action_plan',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='ended_early',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='rubric_version',
            field=models.CharField(default='BOUNDARY-SKILLS-1.0', max_length=30),
        ),
        migrations.AlterField(
            model_name='feedbackscore',
            name='criterion',
            field=models.CharField(choices=[('AGENCY', 'Agency Boundary'), ('RELATIONSHIP', 'Supporter Relationship Boundary'), ('SAFETY', 'Safety & Escalation Boundary'), ('EMPATHY', 'Empathy (legacy)'), ('BOUNDARY_AWARENESS', 'Boundary Awareness (legacy)'), ('REFERRAL_AWARENESS', 'Referral Awareness (legacy)'), ('COMMUNICATION_SKILLS', 'Communication Skills (legacy)')], max_length=40),
        ),
        migrations.AlterField(
            model_name='feedbackscore',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='boundary_type',
            field=models.CharField(choices=[('EMOTIONAL', 'Agency Boundary'), ('BURNOUT', 'Supporter Relationship Boundary'), ('REFERRAL', 'Safety & Escalation Boundary'), ('PRIVACY', 'Integrated Boundary Practice')], max_length=30),
        ),
        migrations.RunPython(
            align_boundary_rubric_scenario_titles,
            migrations.RunPython.noop,
        ),
    ]
