# Generated by Django 6.0.6 on 2026-07-23 21:15

from django.db import migrations, models


TITLE_CHANGES = {
    "EMOTIONAL": (
        ("Emotional Boundary", "Relational Focus Boundary"),
        "Agency Boundary",
    ),
    "BURNOUT": (
        ("Burnout & Compassion Fatigue", "Time & Availability Boundary", "Supporter Relationship Boundary"),
        "Relationship Boundary",
    ),
    "REFERRAL": (
        ("Referral Boundary", "Role Scope & Escalation Boundary", "Safety & Escalation Boundary"),
        "Safety Boundary",
    ),
    "PRIVACY": (
        ("Privacy Boundary", "Privacy & Confidentiality Boundary", "Integrated Boundary Practice"),
        "Integrated Boundary",
    ),
}

PROMPT_LABELS = ("Role Play", "Feedback", "Reflection")


def simplify_boundary_names(apps, schema_editor):
    Scenario = apps.get_model("training", "Scenario")
    Prompt = apps.get_model("training", "Prompt")

    for boundary_type, (old_titles, new_title) in TITLE_CHANGES.items():
        scenario = Scenario.objects.filter(boundary_type=boundary_type).order_by("id").first()
        if scenario is None:
            continue

        if (
            scenario.title in old_titles
            and not Scenario.objects.exclude(pk=scenario.pk).filter(title=new_title).exists()
        ):
            scenario.title = new_title
            scenario.save(update_fields=["title"])

        for prompt_label in PROMPT_LABELS:
            new_name = f"{new_title} {prompt_label} Prompt"
            old_names = [f"{old_title} {prompt_label} Prompt" for old_title in old_titles]
            prompt = (
                Prompt.objects.filter(
                    scenario_id=scenario.id,
                    name__in=old_names,
                )
                .order_by("id")
                .first()
            )
            if prompt and not Prompt.objects.exclude(pk=prompt.pk).filter(name=new_name).exists():
                prompt.name = new_name
                prompt.save(update_fields=["name"])


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0013_feedback_rubric_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackreviewitem',
            name='boundary_key',
            field=models.CharField(choices=[('AGENCY', 'Agency Boundary'), ('RELATIONSHIP', 'Relationship Boundary'), ('SAFETY', 'Safety Boundary')], default='AGENCY', max_length=20),
        ),
        migrations.AlterField(
            model_name='feedbackscore',
            name='criterion',
            field=models.CharField(choices=[('AGENCY', 'Agency Boundary'), ('RELATIONSHIP', 'Relationship Boundary'), ('SAFETY', 'Safety Boundary'), ('EMPATHY', 'Empathy (legacy)'), ('BOUNDARY_AWARENESS', 'Boundary Awareness (legacy)'), ('REFERRAL_AWARENESS', 'Referral Awareness (legacy)'), ('COMMUNICATION_SKILLS', 'Communication Skills (legacy)')], max_length=40),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='boundary_type',
            field=models.CharField(choices=[('EMOTIONAL', 'Agency Boundary'), ('BURNOUT', 'Relationship Boundary'), ('REFERRAL', 'Safety Boundary'), ('PRIVACY', 'Integrated Boundary')], max_length=30),
        ),
        migrations.RunPython(simplify_boundary_names, migrations.RunPython.noop),
    ]
