# Generated by Django 6.0.6 on 2026-07-30 03:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0023_rename_overall_levels_to_scores'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoundaryEvaluationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluator', models.CharField(choices=[('G_EVAL', 'G-Eval')], default='G_EVAL', max_length=20)),
                ('evaluator_version', models.CharField(max_length=40)),
                ('prompt_version', models.CharField(max_length=40)),
                ('rubric_version', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='STARTED', max_length=20)),
                ('response_id', models.CharField(blank=True, max_length=120)),
                ('aggregate_scores', models.JSONField(blank=True, default=dict)),
                ('baseline_rule_scores', models.JSONField(blank=True, default=dict)),
                ('validation_warnings', models.JSONField(blank=True, default=list)),
                ('review_summary', models.TextField(blank=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boundary_evaluation_runs', to='training.trainingsession')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BoundaryTurnEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainee_turn_number', models.PositiveSmallIntegerField()),
                ('boundary_key', models.CharField(choices=[('AGENCY', 'Agency Boundary'), ('RELATIONSHIP', 'Relationship Boundary'), ('SAFETY', 'Safety Boundary')], max_length=20)),
                ('applicable', models.BooleanField(default=True)),
                ('evidence_quotes', models.JSONField(blank=True, default=list)),
                ('evidence_interpretation', models.TextField(blank=True)),
                ('expected_move', models.CharField(blank=True, max_length=255)),
                ('judgement', models.CharField(choices=[('MET', 'Met'), ('PARTLY_MET', 'Partly met'), ('MISSED', 'Missed'), ('BOUNDARY_CONCERN', 'Boundary concern'), ('NOT_APPLICABLE', 'Not applicable')], max_length=30)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rationale', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('critical_concern', models.BooleanField(default=False)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending review'), ('CONFIRMED', 'Confirmed'), ('CORRECTED', 'Corrected'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('corrected_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('corrected_judgement', models.CharField(blank=True, choices=[('MET', 'Met'), ('PARTLY_MET', 'Partly met'), ('MISSED', 'Missed'), ('BOUNDARY_CONCERN', 'Boundary concern'), ('NOT_APPLICABLE', 'Not applicable')], default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('help_seeker_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elicited_boundary_turn_evaluations', to='training.message')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_boundary_turn_evaluations', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turn_evaluations', to='training.boundaryevaluationrun')),
                ('trainee_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boundary_turn_evaluations', to='training.message')),
            ],
            options={
                'ordering': ['trainee_turn_number', 'boundary_key', 'id'],
                'constraints': [models.UniqueConstraint(fields=('run', 'trainee_turn_number', 'boundary_key'), name='unique_boundary_turn_per_evaluation_run')],
            },
        ),
    ]
