# Generated by Django 6.0.6 on 2026-07-30 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0024_boundaryevaluationrun_boundaryturnevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='boundaryevaluationrun',
            name='evaluated_through_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_boundary_evaluation_runs', to='training.message'),
        ),
        migrations.AddField(
            model_name='boundaryevaluationrun',
            name='production_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boundaryevaluationrun',
            name='purpose',
            field=models.CharField(choices=[('MANUAL', 'Manual evaluation'), ('LIVE', 'Live score'), ('FINAL', 'Final feedback')], default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='boundaryevaluationrun',
            name='resolution_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='boundaryevaluationrun',
            name='resolution_status',
            field=models.CharField(choices=[('PENDING', 'Pending resolution'), ('ACCEPTED', 'LLM judgement accepted'), ('FALLBACK', 'Rule fallback used'), ('REVIEW_REQUIRED', 'Human review required')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='boundaryevaluationrun',
            name='resolved_scores',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='boundaryturnevaluation',
            name='expected_move_key',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
