# Generated by Django 6.0.6 on 2026-07-30 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0025_boundaryevaluationrun_evaluated_through_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boundaryevaluationrun',
            name='verification_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_runs', to='training.boundaryevaluationrun'),
        ),
        migrations.AlterField(
            model_name='boundaryevaluationrun',
            name='purpose',
            field=models.CharField(choices=[('MANUAL', 'Manual evaluation'), ('LIVE', 'Live score'), ('FINAL', 'Final feedback'), ('VERIFICATION', 'Verification pass')], default='MANUAL', max_length=20),
        ),
    ]
