# Generated by Django 6.0.6 on 2026-07-30 04:28

import hashlib
from collections import defaultdict

from django.db import migrations, models


KNOWN_REASONS = {
    "LOW_CONFIDENCE",
    "SCORE_DISAGREEMENT",
    "BASELINE_NOT_OBSERVED",
    "CRITICAL_UNCONFIRMED",
}


def select_existing_reviews(apps, schema_editor):
    EvaluationRun = apps.get_model("training", "BoundaryEvaluationRun")
    TurnEvaluation = apps.get_model("training", "BoundaryTurnEvaluation")

    for run in EvaluationRun.objects.prefetch_related(
        "turn_evaluations"
    ).iterator(chunk_size=100):
        by_boundary = defaultdict(list)
        for evaluation in run.turn_evaluations.all():
            by_boundary[evaluation.boundary_key].append(evaluation)

        run_has_pending_required = False
        for boundary_key, evaluations in by_boundary.items():
            already_reviewed = any(
                item.review_status in {"CONFIRMED", "CORRECTED", "REJECTED"}
                for item in evaluations
            )
            details = run.resolution_details or {}
            detail = details.get(boundary_key) or details.get(boundary_key.lower()) or {}

            if already_reviewed:
                scope = "REQUIRED"
                reason = "MANUAL_SELECTION"
            elif detail.get("decision") == "REVIEW_REQUIRED":
                scope = "REQUIRED"
                reason = detail.get("reason_code", "")
                if reason not in KNOWN_REASONS:
                    reason = "RELIABILITY_WARNING"
            elif any(item.critical_concern or item.score == 1 for item in evaluations):
                scope = "REQUIRED"
                reason = "CRITICAL_CONCERN"
            elif run.verification_of_id is None:
                sample_key = (
                    f"{run.session_id}:{run.id}:{boundary_key}".encode("utf-8")
                )
                bucket = int.from_bytes(
                    hashlib.sha256(sample_key).digest()[:8],
                    "big",
                )
                selected = bucket / float(2**64) < 0.10
                scope = "QUALITY_SAMPLE" if selected else "NONE"
                reason = "QUALITY_SAMPLE" if selected else ""
            else:
                scope = "NONE"
                reason = ""

            for evaluation in evaluations:
                evaluation.review_scope = scope
                evaluation.review_reason = reason
                if evaluation.review_status == "PENDING":
                    evaluation.review_status = (
                        "PENDING" if scope != "NONE" else "NOT_REQUIRED"
                    )
                evaluation.save(
                    update_fields=[
                        "review_scope",
                        "review_reason",
                        "review_status",
                    ]
                )
                if scope == "REQUIRED" and evaluation.review_status == "PENDING":
                    run_has_pending_required = True

        if run_has_pending_required:
            run.production_ready = False
            run.resolution_status = "REVIEW_REQUIRED"
            run.save(update_fields=["production_ready", "resolution_status"])


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0026_boundaryevaluationrun_verification_of_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boundaryturnevaluation',
            name='review_reason',
            field=models.CharField(blank=True, choices=[('LOW_CONFIDENCE', 'Low judge confidence'), ('SCORE_DISAGREEMENT', 'Judge and baseline disagree'), ('BASELINE_NOT_OBSERVED', 'Judge found an opportunity the baseline missed'), ('CRITICAL_UNCONFIRMED', 'Critical concern was not independently confirmed'), ('CRITICAL_CONCERN', 'Critical boundary concern'), ('RELIABILITY_WARNING', 'Other reliability warning'), ('QUALITY_SAMPLE', 'Routine quality-control sample'), ('MANUAL_SELECTION', 'Previously selected manually')], default='', max_length=40),
        ),
        migrations.AddField(
            model_name='boundaryturnevaluation',
            name='review_scope',
            field=models.CharField(choices=[('NONE', 'Not selected'), ('REQUIRED', 'Required review'), ('QUALITY_SAMPLE', 'Quality sample')], db_index=True, default='NONE', max_length=20),
        ),
        migrations.RunPython(
            select_existing_reviews,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='boundaryturnevaluation',
            name='review_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not selected for review'), ('PENDING', 'Pending review'), ('CONFIRMED', 'Confirmed'), ('CORRECTED', 'Corrected'), ('REJECTED', 'Rejected')], default='NOT_REQUIRED', max_length=20),
        ),
    ]
