# Generated by Django 6.0.6 on 2026-08-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0028_refresh_system_roleplay_prompts"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedbackscore",
            name="review_required",
            field=models.BooleanField(default=False),
        ),
    ]
